/* USB Net — usb_net_init.c — NCM init.
 *
 * NCM mode uses the well-tested tinyusb_net_init / tinyusb_net_send_sync
 * convenience API.  Descriptors are auto-generated by esp_tinyusb.
 */
#include "usb_net.h"
#include "usb_net_internal.h"

#include "esp_check.h"
#include "esp_log.h"
#include "esp_mac.h"
#include "lwip/esp_netif_net_stack.h"

#include "dhcpserver/dhcpserver.h"

#include "tinyusb.h"
#include "tinyusb_default_config.h"
#include "tinyusb_net.h"

static const char *TAG = "USB_NET_INIT";
static esp_netif_t *s_netif;

static esp_netif_ip_info_t s_ip = {
    .ip      = { .addr = ESP_IP4TOADDR(USB_NET_IP_OCTET1, USB_NET_IP_OCTET2, USB_NET_IP_OCTET3, USB_NET_IP_OCTET4) },
    .gw      = { .addr = ESP_IP4TOADDR(USB_NET_IP_OCTET1, USB_NET_IP_OCTET2, USB_NET_IP_OCTET3, USB_NET_IP_OCTET4) },
    .netmask = { .addr = ESP_IP4TOADDR(USB_NET_NETMASK_O1, USB_NET_NETMASK_O2, USB_NET_NETMASK_O3, USB_NET_NETMASK_O4) },
};

static esp_err_t create_netif(void)
{
    esp_netif_inherent_config_t base = {
        .flags      = ESP_NETIF_DHCP_SERVER | ESP_NETIF_FLAG_AUTOUP,
        .ip_info    = &s_ip,
        .if_key     = "USB_NET",
        .if_desc    = "usb_net (NCM)",
        .route_prio = 60,
        .mtu        = USB_NET_MTU,
    };
    const esp_netif_netstack_config_t stack = {
        .lwip = { .init_fn = ethernetif_init, .input_fn = usb_net_lwip_input },
    };
    esp_netif_driver_ifconfig_t drv = {
        .handle                = (void *)1,
        .transmit              = usb_net_transmit,
        .driver_free_rx_buffer = usb_net_free_rx_buffer,
    };
    const esp_netif_config_t cfg = { .base = &base, .stack = &stack, .driver = &drv };

    s_netif = esp_netif_new(&cfg);
    if (!s_netif) return ESP_ERR_NO_MEM;

    uint8_t mac[6];
    esp_read_mac(mac, ESP_MAC_WIFI_STA);
    mac[0] |= 0x02;
    esp_netif_set_mac(s_netif, mac);
    usb_net_set_recv_netif(s_netif);

    ESP_LOGI(TAG, "USB netif MAC %02x:%02x:%02x:%02x:%02x:%02x",
             mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
    return ESP_OK;
}

static void configure_dhcp(void)
{
    uint32_t lease = USB_NET_DHCP_LEASE_MINUTES * 60;
    esp_netif_dhcps_option(s_netif, ESP_NETIF_OP_SET, ESP_NETIF_IP_ADDRESS_LEASE_TIME, &lease, sizeof(lease));
    dhcps_lease_t pool = {
        .start_ip.addr = ESP_IP4TOADDR(USB_NET_IP_OCTET1, USB_NET_IP_OCTET2, USB_NET_IP_OCTET3, USB_NET_DHCP_START_O4),
        .end_ip.addr   = ESP_IP4TOADDR(USB_NET_IP_OCTET1, USB_NET_IP_OCTET2, USB_NET_IP_OCTET3, USB_NET_DHCP_END_O4),
    };
    esp_netif_dhcps_option(s_netif, ESP_NETIF_OP_SET, ESP_NETIF_REQUESTED_IP_ADDRESS, &pool, sizeof(pool));
}

static esp_err_t init_tinyusb(void)
{
    const tinyusb_config_t cfg = TINYUSB_DEFAULT_CONFIG();
    ESP_RETURN_ON_ERROR(tinyusb_driver_install(&cfg), TAG, "tinyusb_driver_install");

    tinyusb_net_config_t net_cfg = {
        .on_recv_callback = usb_net_tinyusb_recv_cb,
        .free_tx_buffer   = usb_net_tinyusb_free_tx,
        .on_init_callback = usb_net_tinyusb_init_cb,
        .user_context     = s_netif,
    };
    esp_read_mac(net_cfg.mac_addr, ESP_MAC_WIFI_STA);
    net_cfg.mac_addr[0] |= 0x02;

    ESP_RETURN_ON_ERROR(tinyusb_net_init(&net_cfg), TAG, "tinyusb_net_init");
    ESP_LOGI(TAG, "TinyUSB NCM network class ready");
    return ESP_OK;
}

esp_err_t usb_net_init(void)
{
    esp_err_t r;
    if ((r = create_netif()) != ESP_OK)  { ESP_LOGE(TAG, "netif: %s", esp_err_to_name(r)); return r; }
    if ((r = init_tinyusb()) != ESP_OK)  { ESP_LOGE(TAG, "tusb: %s", esp_err_to_name(r));  return r; }

    esp_netif_action_start(s_netif, NULL, 0, NULL);
    esp_netif_action_connected(s_netif, NULL, 0, NULL);
    configure_dhcp();
    return ESP_OK;
}

/* ── TinyUSB NCM callbacks ─────────────────────────────────── */

esp_err_t usb_net_tinyusb_recv_cb(void *buffer, uint16_t len, void *ctx)
{
    if (s_netif) esp_netif_receive(s_netif, buffer, len, NULL);
    return ESP_OK;
}

void usb_net_tinyusb_init_cb(void *ctx)
{
    ESP_LOGI(TAG, "NCM network initialised by host");
}

void usb_net_tinyusb_free_tx(void *buffer, void *ctx)
{
    /* lwIP owns the TX buffer — nothing to free here. */
}
